"use client";

import { useState } from "react";
import { FileText, ListChecks, Sparkles } from "lucide-react";
import { AppShell } from "./AppShell";
import { ArtifactRenderer } from "./ArtifactRenderer";
import { ChatComposer } from "./ChatComposer";
import { RightPane } from "./RightPane";
import { Sidebar } from "./Sidebar";
import { ARTIFACT_SCHEMA_VERSION, type ArtifactSpec } from "./artifact-spec";
import { starterAccountItems, starterConnectors, starterSidebarSections } from "./starter-config";

const demoArtifact: ArtifactSpec = {
  schemaVersion: ARTIFACT_SCHEMA_VERSION,
  id: "starter-plan",
  title: "Agent starter plan",
  summary: "A typed artifact generated by the in-memory demo adapter.",
  status: "complete",
  blocks: [
    {
      id: "summary",
      type: "markdown",
      body: "The reusable shell is connected. Replace this local adapter with your project runtime.",
    },
    {
      id: "tasks",
      type: "task-list",
      title: "Integration checklist",
      items: [
        { id: "router", label: "Connect project routing", status: "pending" },
        { id: "runtime", label: "Connect the chat runtime", status: "pending" },
        { id: "artifact", label: "Map streamed artifact events", status: "done" },
      ],
    },
  ],
};

/**
 * Executable documentation for the package adapter boundary. It intentionally
 * uses local state only and performs no network, auth, model, or provider work.
 */
export function DemoAgenticSurface() {
  const [draft, setDraft] = useState("");
  const [messages, setMessages] = useState<
    Array<{ id: string; role: "user" | "agent"; text: string }>
  >([]);
  const [rightPaneOpen, setRightPaneOpen] = useState(true);
  const [rightPaneMode, setRightPaneMode] = useState("artifact");

  function submit() {
    const text = draft.trim();
    if (!text) return;
    setMessages((current) => [
      ...current,
      { id: `user-${current.length}`, role: "user", text },
      {
        id: `agent-${current.length}`,
        role: "agent",
        text: "I created a typed starter artifact in the work pane.",
      },
    ]);
    setDraft("");
    setRightPaneMode("artifact");
    setRightPaneOpen(true);
  }

  const pane = (
    <RightPane
      title="Starter output"
      modes={[
        { id: "artifact", label: "Artifact", icon: FileText },
        { id: "tasks", label: "Tasks", icon: ListChecks, badge: 3 },
      ]}
      activeMode={rightPaneMode}
      onModeChange={setRightPaneMode}
      onClose={() => setRightPaneOpen(false)}
    >
      {(mode) =>
        mode === "artifact" ? (
          <ArtifactRenderer artifact={demoArtifact} fallback={<p>Artifact unavailable.</p>} />
        ) : (
          <div className="space-y-3 text-sm text-foreground/68">
            <p className="font-medium text-foreground">Project-owned task adapter</p>
            <p>Bind this mode to durable session or workflow task state.</p>
          </div>
        )
      }
    </RightPane>
  );

  return (
    <AppShell
      sidebar={
        <Sidebar
          appName="Agenty"
          sections={starterSidebarSections}
          projects={[{ id: "starter", label: "Starter app", href: "#starter" }]}
          sessions={[{ id: "demo", title: "First agent session", href: "#demo" }]}
          account={{ name: "Demo builder", subtitle: "Local adapter" }}
          accountItems={starterAccountItems}
          activeHref="/"
          onNewChat={() => setMessages([])}
          onSearch={() => undefined}
        />
      }
      rightPane={pane}
      rightPaneOpen={rightPaneOpen}
      onRightPaneClose={() => setRightPaneOpen(false)}
    >
      <header className="flex h-14 shrink-0 items-center justify-between border-b border-foreground/10 px-4">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-foreground/54" />
          <h1 className="text-sm font-medium">Agent session</h1>
        </div>
        {!rightPaneOpen ? (
          <button
            type="button"
            onClick={() => setRightPaneOpen(true)}
            className="rounded-[7px] px-2 py-1 text-xs text-foreground/58 hover:bg-foreground/[0.06] hover:text-foreground"
          >
            Open output
          </button>
        ) : null}
      </header>
      <div className="min-h-0 flex-1 overflow-y-auto px-5 py-8">
        <div className="mx-auto max-w-[760px] space-y-6">
          {messages.length ? (
            messages.map((message) => (
              <div
                key={message.id}
                className={
                  message.role === "user"
                    ? "ml-auto max-w-[80%] rounded-[12px] bg-foreground/[0.065] px-3 py-2 text-sm"
                    : "max-w-[88%] text-sm leading-6 text-foreground/72"
                }
              >
                {message.text}
              </div>
            ))
          ) : (
            <div className="py-20 text-center">
              <h2 className="text-xl font-semibold">What should this agent build?</h2>
              <p className="mt-2 text-sm text-foreground/48">
                This proof surface has no provider or backend dependency.
              </p>
            </div>
          )}
        </div>
      </div>
      <ChatComposer
        value={draft}
        onChange={setDraft}
        onSubmit={submit}
        connectors={starterConnectors}
        selectedConnectorIds={["github"]}
        contextChips={[{ id: "project", label: "Starter app" }]}
      />
    </AppShell>
  );
}
